---
title: "Regex"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,error=TRUE,collapse = T)
library(reticulate)

py_require('pandas')
py_require('numpy')
py_require('psutil')
```

<style>
div.python pre { background-color: #e9f7f5
; }
</style>

<style>
div.r pre { background-color: #fff5fd; }
</style>


# Strings

## Manipulate strings

<div class = "row">
<div class = "python">


```{python, collapse = T}
# Python 
import os

wd_t = r'C:\Users\mypath\to\myfolder'
wd_t
print(wd_t)
```


- The purpose of the r'...' notation is to create raw strings and use different rules for interpreting backslash escape sequences. There is no need to use r if you're just getting the value from another variable.

- In Python, a string can be treated as an array, and it's easy to select specific pieces of the string using the position of the letters. In R, a string is a block that needs to be decomposed in order to select specific letters. The number of characters in a string is its length. Strings can be modified in various ways, which are listed in the following link: https://www.w3schools.com/python/python_ref_string.asp . Some examples are provided there.

```{python , collapse = T, error= T}
# Python 

wd_info = 'Current working directory:\n'+os.getcwd()
slc_infos = wd_info[10:20]
len(slc_infos)
slc_infos
slc_infos = list(slc_infos)
slc_infos

# mutable
slc_infos[7] = '0'
slc_infos

# count
wd_info.count('s')

# modify the string
wd_info.title()
wd_info.upper()
wd_info.lower()
splt_inf = wd_info.split(': ')
splt_inf
' '.join(splt_inf)

```



```{python , collapse = T}
import numpy as np

"".join(['a :','1','b :','2','c :','3'])
" ".join(['a :','1','b :','2','c :','3'])


[''.join([letter,number]) for letter, number in zip(['a :','b :','c :'],['1','2','3'])]
list(map(''.join,zip(['a :','b :','c :'],['1','2','3'])))
'.'.join((np.char.array(['a :','b :','c :'])+np.char.array(['1','2','3'])).tolist())


np.char.array([['a :','b :','c :']])+'O'

```

</div>
</div>

<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">


**Exercise 1:** Write a Python expression that converts the string "python programming" to uppercase.

<details>
<summary>Click here to see the solution</summary>
```{python,echo = T,collapse = TRUE}
text = "python programming"
uppercase_text = text.upper()
print(uppercase_text)
```
</details>  

</div>

<p>&nbsp;</p>

## Escape character

<div class = "row">
<div class = "python">

```{python , collapse = T}
# Python 
import time
import psutil
import os

time_ = time.ctime(time.time())
time_info = 'Time: '
wd = os.getcwd()
wd_info = '\nCurrent working directory: '

infos = time_info+time_+wd_info+wd

print(infos)

```



</div>
</div>


Here is some information on the computer where this document was created:

The working directory is the path to the folder where we are currently working. If we read or write a file without specifying the exact path (only the name of the file), the program will search for the file in the current working directory.

'\\' is the backslash character and is used to specify special characters, tabulation, new lines, backslashes or quotes, etc. When working with file paths, this can be confusing for the machine. To avoid this, we can specify that the string must be read as it is by using 'r' before the quotation mark.

Here is a list of escape characters that can be useful:

 Escape Sequence | Description 
- | -:
 \\t 	| Insert a tab in the text at this point.
 \\b 	| Insert a backspace in the text at this point.
 \\n 	| Insert a newline in the text at this point.
 \\r 	| Insert a carriage return in the text at this point.
 \\f 	| Insert a form feed in the text at this point.
 \\' 	| Insert a single quote character in the text at this point.
 \\" 	| Insert a double quote character in the text at this point.
 \\\ 	| Insert a backslash character in the text at this point.   


## Formatted strings

 - In Python, the % sign is used for producing formatted output. Another way to format output is to use the "{}".format() method, which allows for the automatic replacement of values in a raw text. Let's rewrite our function using this method.
 
<div class = "row">
<div class = "python">

```{python , collapse = T}
# Python 

def get_infos():
  time_info = 'Time: '+time.ctime(time.time())
  wd_info = '\nCurrent working directory: '+os.getcwd()
  infos = time_info+wd_info
  print(infos)


def get_infos_2():
  infos = '''Time: %s 
Current working directory: %s'''% (time.ctime(time.time()),
  os.getcwd())
  print(infos)
  
def get_infos_3():
  infos = '''Time: {t} 
Current working directory: {wd}'''.format(t = time.ctime(time.time()),
  wd = os.getcwd())
  print(infos)
  
  

get_infos()

get_infos_2()

get_infos_3()

```
</div>
</div>


# Regular Expressions

- Text used in this section is the abstract of 'ImageNet Classification with Deep Convolutional Neural Networks' (Alex Krizhevsky, Ilya Sutskever, and Geoffrey E. Hinton 2012) presented at 'Advances in Neural Information Processing Systems 25' (NIPS 2012)



```
'<p>We trained a large, deep convolutional neural network to classify the 1.3 million 
high-resolution images in the LSVRC-2010 ImageNet training set into the 1000 different 
classes. On the test data, we achieved top-1 and top-5 error rates of 39.7\% and
18.9\% which is considerably better than the previous state-of-the-art results.
The neural network, which has 60 million parameters and 500,000 neurons,
consists of five convolutional layers, some of which are followed by max-pooling
layers, and two globally connected layers with a final 1000-way softmax.
To make training faster, we used non-saturating neurons and a very efficient GPU
implementation of convolutional nets. To reduce overfitting in the globally
connected layers we employed a new regularization method that proved to be very effective.</p>'
```

- Regular expressions (regex) are a way to express how a character sequence should be matched, and are a very flexible tool. They are commonly used in text manipulation and are used by string-searching algorithms for "find" or "find and replace" operations on strings, or for input validation.

- Except for control characters (+ ? . * ^ $ ( ) [ ] { } | \ ), all characters match themselves. You can escape a control character by preceding it with a backslash.

- Some functions in 're' (Python) and 'stringr'(R) that can be useful when working with regular expressions are:

Re | Stringr |Description
-|:-|-:
findall |	str_match_all | Returns a list containing all matches
finditer | |	Returns a iterator containing all matches
search |	str_locate_all |Returns a Match object if there is a match anywhere in the string
split | str_split | 	Returns a list where the string has been split at each match
sub | str_replace_all |	Replaces one or many matches with a string

- Metacharacters are characters that have a special meaning in regular expressions. Their uses are discussed in more detail in the next few sections.

- Parentheses ( ) are used for grouping. Square brackets [ ] define a character class, and curly braces { } are used by a quantifier with specific limits.

Character |	Description |	Example
-|:-|-:
[] |	A set of characters | "[a-m]" 	
\ |	Signals a special sequence (can also be used to escape special characters)| 	"\\d" 	
. |	Any character (except newline character) |	"he..o" 	
^ |	Starts with |	"^hello" 	
\$ |	Ends with |	"world$" 	
* |	Zero or more occurrences |	"aix*" 	
+ |	One or more occurrences |	"aix+" 	
{} |	Exactly the specified number of occurrences |	"al{2}" 	
\| |	Either or |	"x\|y"
() | Grouping characters (or other regexes) |"(ab)\1" matches "abab"

<div class = "row">
<div class = "python">

```{python,echo = T,collapse = TRUE}
# Python 
import re

abstract = open("data/imagenet_abstract.txt", "r").read()
 
re.search('layers',abstract)

re.findall('layers',abstract)

re.findall('net+','net ne nett networks')

re.findall('net*','net ne nett networks')



re.sub(r'\\','',abstract)

re.split(' ',abstract)[:5]


```

</div>
</div>

<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">

**Exercise 1:** Write a Python expression using regex that finds all occurrences of the word "data" in the string "data science and big data analytics".

<details>
<summary>Click here to see the solution</summary>
```{python,echo = T,collapse = TRUE}
import re
text = "data science and big data analytics"
matches = re.findall('data', text)
print(matches)
```
</details>  

<p>&nbsp;</p>

**Exercise 2:** Write a Python expression using regex that replaces all spaces with underscores in the string "hello world python".

<details>
<summary>Click here to see the solution</summary>
```{python,echo = T,collapse = TRUE}
import re
text = "hello world python"
result = re.sub(' ', '_', text)
print(result)
```
</details>  

</div>

<p>&nbsp;</p>

## Anchors


Example|Description
-|-:
^Python|Match "Python" at the start of a string 
Python$|Match "Python" at the end of a string
\\APython|Match "Python" at the start of a string
Python\\Z|Match "Python" at the end of a string
\\bPython\\b|Match "Python" at a word boundary
\\brub\\B|\\B is nonword boundary: match "rub" in "rube" and "ruby" but not alone
Python(?=!)|Match "Python", if followed by an exclamation point.
Python(?!!)|Match "Python", if not followed by an exclamation point.

<div class = "row">
<div class = "python">

```{python,echo = T,collapse = TRUE}
# Python 
import re

words = ['neuron','neural','network','networks','deep convolutional neural network']

[w for w in words if re.match(r'\Aneu',w)]
[w for w in words if re.match(r'^neu',w)]
[w for w in words if re.match(r'works?\Z',w)]
[w for w in words if re.match(r'works?$',w)]


```

</div>
</div>

## Character classes

Example|Description
-|-:
[Pp]ython|Match "Python" or "python"
rub[ye]|Match "ruby" or "rube"
[aeiou]|Match any one lowercase vowel
[0-9]|Match any digit; same as [0123456789]
[a-z]|Match any lowercase ASCII letter
[A-Z]|Match any uppercase ASCII letter
[a-zA-Z0-9]|Match any of the above
[^aeiou]|Match anything other than a lowercase vowel
[^0-9]|Match anything other than a digit

<div class = "row">
<div class = "python">

```{python,echo = T,collapse = TRUE}
# Python 
import re

re.findall('top-[15]',abstract)

# you can also create an iterator
re.finditer('[0-9]',abstract)


```

</div>
</div>

<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">

**Exercise 1:** Write a Python expression using regex that finds all vowels (a, e, i, o, u) in the string "beautiful".

<details>
<summary>Click here to see the solution</summary>
```{python,echo = T,collapse = TRUE}
import re
text = "beautiful"
vowels = re.findall('[aeiou]', text)
print(vowels)
```
</details>  

<p>&nbsp;</p>

**Exercise 2:** Write a Python expression using regex that extracts all uppercase letters from the string "Hello World PYTHON".

<details>
<summary>Click here to see the solution</summary>
```{python,echo = T,collapse = TRUE}
import re
text = "Hello World PYTHON"
uppercase = re.findall('[A-Z]', text)
print(uppercase)
```
</details>  

</div>

<p>&nbsp;</p>

## Special Character Classes

Example|Description
-|-:
.|Match any character except newline
\\d|Match a digit: [0-9]
\\D|Match a nondigit: [^0-9]
\\s|Match a whitespace character: [ \\t\\r\\n\\f]
\\S|Match nonwhitespace: [^ \\t\\r\\n\\f]
\\w|Match a single word character: [A-Za-z0-9_]
\\W|Match a nonword character: [^A-Za-z0-9_]

<div class = "row">
<div class = "python">

```{python,echo = T,collapse = TRUE}
# Python 
import re

re.sub('\w','',abstract)

re.search('\d',abstract)

```

</div>
</div>

<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">

**Exercise 1:** Write a Python expression using regex that finds all digits in the string "Room 123, Floor 4".

<details>
<summary>Click here to see the solution</summary>
```{python,echo = T,collapse = TRUE}
import re
text = "Room 123, Floor 4"
digits = re.findall('\d', text)
print(digits)
```
</details>  

</div>

<p>&nbsp;</p>

## Repetition Cases

Example|Description
-|-:
ruby?|Match "rub" or "ruby": the y is optional
ruby*|Match "rub" plus 0 or more ys
ruby+|Match "rub" plus 1 or more ys
\\d{3}|Match exactly 3 digits
\\d{3,}|Match 3 or more digits
\\d{3,5}|Match 3, 4, or 5 digits

Nongreedy repetition
This matches the smallest number of repetitions

Example|Description
-|-:	
<.*>|Greedy repetition: matches ```"<python>perl>"```
<.*?>|Nongreedy: matches ```"<python>"``` in ```"<python>perl>"```

<div class = "row">
<div class = "python">

```{python,echo = T,collapse = TRUE}
# Python 
import re

re.findall('\d{2,4}',abstract)

re.findall(r'[[].*[]]',r'[[Hello] World]')
re.findall(r'[[].*?[]]',r'[[Hello] World]')


```

</div>
</div>

<p>&nbsp;</p>

<div style="border:1px solid; padding:10px; margin-bottom:10px; border-radius: 10px; background-color: #f9f9f9;">

**Exercise 1:** Write a Python expression using regex that finds all phone numbers in the format XXX-XXXX (3 digits, hyphen, 4 digits) in the string "Call 123-4567 or 987-6543".

<details>
<summary>Click here to see the solution</summary>
```{python,echo = T,collapse = TRUE}
import re
text = "Call 123-4567 or 987-6543"
phone_numbers = re.findall('\d{3}-\d{4}', text)
print(phone_numbers)
```
</details>  

</div>

<p>&nbsp;</p>

## Grouping with Parentheses

Example|Description
-|-:
\\D\\d+|No group: + repeats \\d
(\\D\\d)+|Grouped: + repeats \\D\\d pair

<div class = "row">
<div class = "python">

```{python,echo = T,collapse = TRUE}
# Python 

re.findall('[A-Z]\d+', "A8 DF Z7 376 A28 A0A4A8")

re.findall('([A-Z]\d)+', "A8 DF Z7 376 A28 A0A4A8")

re.findall('(?:[A-Z]\d)+', "A8 DF Z7 376 A28 A0A4A8")
# ?: in this context tells Python's regex library to not consider the parentheses as defining a capture. (It's still used for grouping)
# normal capture group will hinder ability to get whole match
# non-capturing group to the rescue

list(re.finditer('([A-Z]\d)+', "A8 DF Z7 376 A28 A0A4A8"))

[i.group() for i in re.finditer('[A-Z]\d+', "A8 DF Z7 376 A28 A0A4A8")]

[i.group() for i in re.finditer('([A-Z]\d)+', "A8 DF Z7 376 A28 A0A4A8")]

```

</div>
</div>
## Backreferences
This matches a previously matched group again

Example|Description
-|-:
([Pp])ython&\\1ails|Match python&pails or Python&Pails
(['"])[^\\1]*\\1|Single or double-quoted string. \\1 matches whatever the 1st group matched. \\2 matches whatever the 2nd group matched, etc.

Alternatives

	
python|perl : Match "python" or "perl"

rub(y|le)) : Match "ruby" or "ruble"

Python(!+|\\?) : Match "Python" followed by one or more ! or one ?

<div class = "row">
<div class = "python">

```{python,echo = T,collapse = TRUE,error = T}
# Python 
import re

re.sub(r'\[(\d+)\]', r'\1', '[38] min and [4] sec')

re.sub(r'\[(\d+)\]', r'\1 long', '[38] min and [4] sec')

re.sub(r'\[(\d+)\]', r'\10', '[38] min and [4] sec')

re.sub(r'\[(\d+)\]', r'\g<1>0', '[38] min and [4] sec')


```

</div>
</div>

# Exercise

Here is the list of all university restaurants in strasbourg, could you create a program that would enable us to compare the menus of open university restaurants in Strasbourg for the next three days ? To do this, please go to the web page on your browser, inspect it by right-clicking, and find the correct HTML class.

https://www.crous-strasbourg.fr/se-restaurer/ou-manger/


Here's how you can start in Python:

  - Visit https://www.whatismybrowser.com/detect/what-is-my-user-agent/ and copy your User Agent information (for example: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"). Paste this information below into the user_agent dictionary.

  - Use the function get_page(url_page) to retrieve the HTML content from the webpage.

```
import requests
import time 
import random


user_agent = {'User-Agent':'YOUR/USER-AGENT/INFOS/HERE'}


def get_page(urlpage):
    # Avoid getting ban
    time.sleep(7 + random.uniform(0,8))
    # Get the html from the webpage
    res = requests.get(urlpage, headers = user_agent)
    return res.text

urlpage = 'https://www.crous-strasbourg.fr/restaurant/resto-u-esplanade/'
page = get_page(urlpage)

menus = re.findall(r'<div class="menu">.*?</ul>\s*</div>\s*</div>', page, re.DOTALL)

```

<a href="resto_u_explication.html">Detailled solution</a> 


<!--
resto_u_explication.html
Here is an other very simple webscrapping example where we scrap rap-genius to get lyrics from all songs in the album '13 Organisé', for each artist we count the number of unique words after remooving stopwords.


<a href="4_Regex.html">Example with 'rap genius'</a> -->
